### ISSUE TITLE
Manifest file should be updated!

### ISSUE THREAD

**Issue by MasoudRahmani** [endenizen/extensioner#1]
hi thanks for great extension.
now chrome dont accept your extension and cant load this manifest , it needs to be updated.
i updated your manifest but it has CSP error

> refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

when running this line of code
`<body class="popup" onload="setupPopupPage()">`

update: i solved it. if you think it works. merge

**Comment by endenizen** [comment]
Why does the manifest need to be updated? It seems to work fine. I can uninstall and reinstall from the store. What isn't working for you?

**Comment by MasoudRahmani** [comment]
i am using chrome _Version 67.0.3396.79 (Official Build) (64-bit)_ and when downloading from store
![untitled](https://user-images.githubusercontent.com/5321268/41187016-f350c8e6-6bb6-11e8-8c04-365b04e2ec32.jpg)


@endenizen any suggestion?

**Comment by endenizen** [comment]
Ah ok, I updated and now I see the same issue! Thanks for sending some PRs, I'll take a look.

**Comment by endenizen** [comment]
I published the changes to the store from your PRs, so this should be fixed for people updating to the latest chrome. So no rush on merging PRs. I appreciate your quick fixes!

**Comment by MasoudRahmani** [comment]
thanks, i look forward to use your great extension. 
thank YOU
